import { configureStore as configureStoreToolkit } from '@reduxjs/toolkit';
import { Action, CreateReduxPackAction, CreateReduxPackFn, CreateReduxPackType } from './types';
import { OutputSelector } from 'reselect';
declare const createReduxPack: CreateReduxPackFn & CreateReduxPackType;
declare const enableLogger: () => void;
declare const disableLogger: () => void;
declare const createSelector: <T>(reducerName: string, stateKey: string) => OutputSelector<any, T, (res: any) => T>;
declare const createAction: <Payload, Result>(name: string, formatPayload?: ((data: Payload) => Result) | undefined) => CreateReduxPackAction<Payload, Payload | Result>;
declare const configureStore: (options: Omit<Parameters<typeof configureStoreToolkit>[0], 'reducer'>) => ReturnType<typeof configureStoreToolkit>;
declare const createReducerOn: <S>(reducerName: string, initialState: S, actionMap: Record<string, (state: S, action: Action<any>) => S>) => void;
export { createSelector, createAction, configureStore, enableLogger, disableLogger, createReducerOn };
export default createReduxPack;
